import { GameType } from './types';

export interface GameThemeConfig {
  type: GameType | 'DEFAULT';
  title: string;
  brandTitle: string;
  badge: string;
  primaryColor: string;
  bgGradient: string;
  navbarBg: string;
  navbarBorder: string;
  navbarBrandGrad: string;
  navIconBg: string;
  cardBorder: string;
  accentBadgeBg: string;
  accentBadgeText: string;
  accentBadgeBorder: string;
  buttonGrad: string;
  turnBannerMyTurn: string;
  turnBannerWaiting: string;
  tickerGlow: string;
}

export const GAME_THEMES: Record<GameType | 'DEFAULT', GameThemeConfig> = {
  BINGO: {
    type: 'BINGO',
    title: 'Bingo Multiplayer',
    brandTitle: 'BINGO',
    badge: 'Classic 2-6 Players',
    primaryColor: '#f8788a',
    bgGradient: 'from-[#fed7e2] via-[#fce7f3] to-[#f3e8ff]',
    navbarBg: 'bg-white/85 border-[#fbcfe8]',
    navbarBorder: 'border-[#fbcfe8]',
    navbarBrandGrad: 'from-[#f8788a] via-[#e271a5] to-[#f43f5e]',
    navIconBg: 'from-[#f8788a] to-[#e11d48]',
    cardBorder: 'border-[#fbcfe8]',
    accentBadgeBg: 'bg-[#fee8ea]',
    accentBadgeText: 'text-[#e11d48]',
    accentBadgeBorder: 'border-[#fcd3d7]',
    buttonGrad: 'from-[#f8788a] via-[#e271a5] to-[#e11d48]',
    turnBannerMyTurn: 'bg-[#fff1f2] border-2 border-[#f43f5e] ring-4 ring-[#f43f5e]/20 shadow-[0_8px_24px_rgba(244,63,94,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#fcd3d7]',
    tickerGlow: 'bg-[#fee8ea] border-[#fcd3d7] text-[#e11d48]',
  },
  TIC_TAC_TOE: {
    type: 'TIC_TAC_TOE',
    title: 'Tic-Tac-Toe Duel',
    brandTitle: 'TIC-TAC-TOE',
    badge: '1v1 Duel',
    primaryColor: '#8b5cf6',
    bgGradient: 'from-[#ede9fe] via-[#e0e7ff] to-[#f5d0fe]',
    navbarBg: 'bg-white/85 border-[#ddd6fe]',
    navbarBorder: 'border-[#ddd6fe]',
    navbarBrandGrad: 'from-[#8b5cf6] via-[#7c3aed] to-[#ec4899]',
    navIconBg: 'from-[#8b5cf6] to-[#ec4899]',
    cardBorder: 'border-[#ddd6fe]',
    accentBadgeBg: 'bg-[#f5f3ff]',
    accentBadgeText: 'text-[#7c3aed]',
    accentBadgeBorder: 'border-[#ddd6fe]',
    buttonGrad: 'from-[#8b5cf6] via-[#7c3aed] to-[#ec4899]',
    turnBannerMyTurn: 'bg-[#f5f3ff] border-2 border-[#8b5cf6] ring-4 ring-[#8b5cf6]/20 shadow-[0_8px_24px_rgba(139,92,246,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#ddd6fe]',
    tickerGlow: 'bg-[#f5f3ff] border-[#ddd6fe] text-[#7c3aed]',
  },
  DOTS_AND_BOXES: {
    type: 'DOTS_AND_BOXES',
    title: 'Dots & Boxes',
    brandTitle: 'DOTS & BOXES',
    badge: 'Strategy 2-4 Players',
    primaryColor: '#10b981',
    bgGradient: 'from-[#ccfbf1] via-[#d1fae5] to-[#e0f2fe]',
    navbarBg: 'bg-white/85 border-[#a7f3d0]',
    navbarBorder: 'border-[#a7f3d0]',
    navbarBrandGrad: 'from-[#10b981] via-[#059669] to-[#0284c7]',
    navIconBg: 'from-[#10b981] to-[#0284c7]',
    cardBorder: 'border-[#a7f3d0]',
    accentBadgeBg: 'bg-[#ecfdf5]',
    accentBadgeText: 'text-[#047857]',
    accentBadgeBorder: 'border-[#a7f3d0]',
    buttonGrad: 'from-[#10b981] via-[#059669] to-[#0284c7]',
    turnBannerMyTurn: 'bg-[#ecfdf5] border-2 border-[#10b981] ring-4 ring-[#10b981]/20 shadow-[0_8px_24px_rgba(16,185,129,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#a7f3d0]',
    tickerGlow: 'bg-[#ecfdf5] border-[#a7f3d0] text-[#047857]',
  },
  CONNECT_FOUR: {
    type: 'CONNECT_FOUR',
    title: 'Connect Four',
    brandTitle: 'CONNECT 4',
    badge: '1v1 Vertical Duel',
    primaryColor: '#2563eb',
    bgGradient: 'from-[#dbeafe] via-[#eff6ff] to-[#fef3c7]',
    navbarBg: 'bg-white/85 border-[#bfdbfe]',
    navbarBorder: 'border-[#bfdbfe]',
    navbarBrandGrad: 'from-[#2563eb] via-[#3b82f6] to-[#f59e0b]',
    navIconBg: 'from-[#2563eb] to-[#f59e0b]',
    cardBorder: 'border-[#bfdbfe]',
    accentBadgeBg: 'bg-[#eff6ff]',
    accentBadgeText: 'text-[#1d4ed8]',
    accentBadgeBorder: 'border-[#bfdbfe]',
    buttonGrad: 'from-[#2563eb] via-[#1d4ed8] to-[#f59e0b]',
    turnBannerMyTurn: 'bg-[#eff6ff] border-2 border-[#2563eb] ring-4 ring-[#2563eb]/20 shadow-[0_8px_24px_rgba(37,99,235,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#bfdbfe]',
    tickerGlow: 'bg-[#eff6ff] border-[#bfdbfe] text-[#1d4ed8]',
  },
  ROCK_PAPER_SCISSORS: {
    type: 'ROCK_PAPER_SCISSORS',
    title: 'Rock Paper Scissors',
    brandTitle: 'RPS DUEL',
    badge: 'Best of 5 Duel',
    primaryColor: '#ea580c',
    bgGradient: 'from-[#ffedd5] via-[#fff7ed] to-[#fee2e2]',
    navbarBg: 'bg-white/85 border-[#fed7aa]',
    navbarBorder: 'border-[#fed7aa]',
    navbarBrandGrad: 'from-[#ea580c] via-[#f97316] to-[#ef4444]',
    navIconBg: 'from-[#ea580c] to-[#ef4444]',
    cardBorder: 'border-[#fed7aa]',
    accentBadgeBg: 'bg-[#fff7ed]',
    accentBadgeText: 'text-[#c2410c]',
    accentBadgeBorder: 'border-[#fed7aa]',
    buttonGrad: 'from-[#ea580c] via-[#f97316] to-[#ef4444]',
    turnBannerMyTurn: 'bg-[#fff7ed] border-2 border-[#ea580c] ring-4 ring-[#ea580c]/20 shadow-[0_8px_24px_rgba(234,88,12,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#fed7aa]',
    tickerGlow: 'bg-[#fff7ed] border-[#fed7aa] text-[#c2410c]',
  },
  MEMORY: {
    type: 'MEMORY',
    title: 'Memory Match',
    brandTitle: 'MEMORY',
    badge: 'Card Flip Match',
    primaryColor: '#7c3aed',
    bgGradient: 'from-[#ede9fe] via-[#f5f3ff] to-[#fce7f3]',
    navbarBg: 'bg-white/85 border-[#ddd6fe]',
    navbarBorder: 'border-[#ddd6fe]',
    navbarBrandGrad: 'from-[#7c3aed] via-[#8b5cf6] to-[#ec4899]',
    navIconBg: 'from-[#7c3aed] to-[#ec4899]',
    cardBorder: 'border-[#ddd6fe]',
    accentBadgeBg: 'bg-[#f5f3ff]',
    accentBadgeText: 'text-[#6d28d9]',
    accentBadgeBorder: 'border-[#ddd6fe]',
    buttonGrad: 'from-[#7c3aed] via-[#6d28d9] to-[#ec4899]',
    turnBannerMyTurn: 'bg-[#f5f3ff] border-2 border-[#7c3aed] ring-4 ring-[#7c3aed]/20 shadow-[0_8px_24px_rgba(124,58,237,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#ddd6fe]',
    tickerGlow: 'bg-[#f5f3ff] border-[#ddd6fe] text-[#6d28d9]',
  },
  NUMBER_RUSH: {
    type: 'NUMBER_RUSH',
    title: 'Number Rush',
    brandTitle: 'NUMBER RUSH',
    badge: 'Speed Tap Race',
    primaryColor: '#0891b2',
    bgGradient: 'from-[#cffafe] via-[#ecfeff] to-[#d1fae5]',
    navbarBg: 'bg-white/85 border-[#a5f3fc]',
    navbarBorder: 'border-[#a5f3fc]',
    navbarBrandGrad: 'from-[#0891b2] via-[#06b6d4] to-[#10b981]',
    navIconBg: 'from-[#0891b2] to-[#10b981]',
    cardBorder: 'border-[#a5f3fc]',
    accentBadgeBg: 'bg-[#ecfeff]',
    accentBadgeText: 'text-[#0e7490]',
    accentBadgeBorder: 'border-[#a5f3fc]',
    buttonGrad: 'from-[#0891b2] via-[#06b6d4] to-[#10b981]',
    turnBannerMyTurn: 'bg-[#ecfeff] border-2 border-[#0891b2] ring-4 ring-[#0891b2]/20 shadow-[0_8px_24px_rgba(8,145,178,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#a5f3fc]',
    tickerGlow: 'bg-[#ecfeff] border-[#a5f3fc] text-[#0e7490]',
  },
  WORD_SCRAMBLE: {
    type: 'WORD_SCRAMBLE',
    title: 'Word Scramble',
    brandTitle: 'WORD SCRAMBLE',
    badge: 'Anagram Race',
    primaryColor: '#0d9488',
    bgGradient: 'from-[#ccfbf1] via-[#f0fdfa] to-[#fef3c7]',
    navbarBg: 'bg-white/85 border-[#99f6e4]',
    navbarBorder: 'border-[#99f6e4]',
    navbarBrandGrad: 'from-[#0d9488] via-[#14b8a6] to-[#f59e0b]',
    navIconBg: 'from-[#0d9488] to-[#f59e0b]',
    cardBorder: 'border-[#99f6e4]',
    accentBadgeBg: 'bg-[#f0fdfa]',
    accentBadgeText: 'text-[#0f766e]',
    accentBadgeBorder: 'border-[#99f6e4]',
    buttonGrad: 'from-[#0d9488] via-[#0f766e] to-[#f59e0b]',
    turnBannerMyTurn: 'bg-[#f0fdfa] border-2 border-[#0d9488] ring-4 ring-[#0d9488]/20 shadow-[0_8px_24px_rgba(13,148,136,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#99f6e4]',
    tickerGlow: 'bg-[#f0fdfa] border-[#99f6e4] text-[#0f766e]',
  },
  SHIP_BATTLE: {
    type: 'SHIP_BATTLE',
    title: 'Ship Battle',
    brandTitle: 'SHIP BATTLE',
    badge: '1v1 Naval Duel',
    primaryColor: '#0284c7',
    bgGradient: 'from-[#bae6fd] via-[#e0f2fe] to-[#c7d2fe]',
    navbarBg: 'bg-white/85 border-[#7dd3fc]',
    navbarBorder: 'border-[#7dd3fc]',
    navbarBrandGrad: 'from-[#0284c7] via-[#0369a1] to-[#1e3a8a]',
    navIconBg: 'from-[#0284c7] to-[#1e3a8a]',
    cardBorder: 'border-[#7dd3fc]',
    accentBadgeBg: 'bg-[#e0f2fe]',
    accentBadgeText: 'text-[#0369a1]',
    accentBadgeBorder: 'border-[#7dd3fc]',
    buttonGrad: 'from-[#0284c7] via-[#0369a1] to-[#1e3a8a]',
    turnBannerMyTurn: 'bg-[#e0f2fe] border-2 border-[#0284c7] ring-4 ring-[#0284c7]/20 shadow-[0_8px_24px_rgba(2,132,199,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#7dd3fc]',
    tickerGlow: 'bg-[#e0f2fe] border-[#7dd3fc] text-[#0369a1]',
  },
  DEFAULT: {
    type: 'DEFAULT',
    title: 'Multi Arcade',
    brandTitle: 'ARCADE HUB',
    badge: 'Multiplayer Games',
    primaryColor: '#8b7fe8',
    bgGradient: 'from-[#d9d2fa] via-[#e8e2fc] to-[#fde2ea]',
    navbarBg: 'bg-white/80 border-[#ede8f8]',
    navbarBorder: 'border-[#ede8f8]',
    navbarBrandGrad: 'from-[#f8788a] via-[#e271a5] to-[#8b7fe8]',
    navIconBg: 'from-[#f8788a] via-[#e271a5] to-[#8b7fe8]',
    cardBorder: 'border-[#ede8f8]',
    accentBadgeBg: 'bg-[#f0ecfc]',
    accentBadgeText: 'text-[#6d5ebd]',
    accentBadgeBorder: 'border-[#e0d6f8]',
    buttonGrad: 'from-[#f8788a] via-[#e271a5] to-[#8b7fe8]',
    turnBannerMyTurn: 'bg-[#f0ecfc] border-2 border-[#8b7fe8] ring-4 ring-[#8b7fe8]/20 shadow-[0_8px_24px_rgba(139,127,232,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#ede8f8]',
    tickerGlow: 'bg-[#f0ecfc] border-[#e0d6f8] text-[#6d5ebd]',
  },
};

export const getGameTheme = (gameType?: GameType | 'DEFAULT' | null): GameThemeConfig => {
  if (gameType && GAME_THEMES[gameType]) {
    return GAME_THEMES[gameType];
  }
  return GAME_THEMES.DEFAULT;
};
