import { GameType } from './types';

export interface GameThemeConfig {
  type: GameType | 'DEFAULT';
  title: string;
  brandTitle: string;
  badge: string;
  primaryColor: string;
  bgGradient: string;
  navbarBg: string;
  navbarBorder: string;
  navbarBrandGrad: string;
  navIconBg: string;
  cardBorder: string;
  accentBadgeBg: string;
  accentBadgeText: string;
  accentBadgeBorder: string;
  buttonGrad: string;
  turnBannerMyTurn: string;
  turnBannerWaiting: string;
  tickerGlow: string;
}

export const GAME_THEMES: Record<GameType | 'DEFAULT', GameThemeConfig> = {
  BINGO: {
    type: 'BINGO',
    title: 'Bingo Multiplayer',
    brandTitle: 'BINGO',
    badge: 'Classic 2-6 Players',
    primaryColor: '#f8788a',
    bgGradient: 'from-[#fed7e2] via-[#fce7f3] to-[#f3e8ff]',
    navbarBg: 'bg-white/85 border-[#fbcfe8]',
    navbarBorder: 'border-[#fbcfe8]',
    navbarBrandGrad: 'from-[#f8788a] via-[#e271a5] to-[#f43f5e]',
    navIconBg: 'from-[#f8788a] to-[#e11d48]',
    cardBorder: 'border-[#fbcfe8]',
    accentBadgeBg: 'bg-[#fee8ea]',
    accentBadgeText: 'text-[#e11d48]',
    accentBadgeBorder: 'border-[#fcd3d7]',
    buttonGrad: 'from-[#f8788a] via-[#e271a5] to-[#e11d48]',
    turnBannerMyTurn: 'bg-[#fff1f2] border-2 border-[#f43f5e] ring-4 ring-[#f43f5e]/20 shadow-[0_8px_24px_rgba(244,63,94,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#fcd3d7]',
    tickerGlow: 'bg-[#fee8ea] border-[#fcd3d7] text-[#e11d48]',
  },
  TIC_TAC_TOE: {
    type: 'TIC_TAC_TOE',
    title: 'Tic-Tac-Toe Duel',
    brandTitle: 'TIC-TAC-TOE',
    badge: '1v1 Duel',
    primaryColor: '#8b5cf6',
    bgGradient: 'from-[#ede9fe] via-[#e0e7ff] to-[#f5d0fe]',
    navbarBg: 'bg-white/85 border-[#ddd6fe]',
    navbarBorder: 'border-[#ddd6fe]',
    navbarBrandGrad: 'from-[#8b5cf6] via-[#7c3aed] to-[#ec4899]',
    navIconBg: 'from-[#8b5cf6] to-[#ec4899]',
    cardBorder: 'border-[#ddd6fe]',
    accentBadgeBg: 'bg-[#f5f3ff]',
    accentBadgeText: 'text-[#7c3aed]',
    accentBadgeBorder: 'border-[#ddd6fe]',
    buttonGrad: 'from-[#8b5cf6] via-[#7c3aed] to-[#ec4899]',
    turnBannerMyTurn: 'bg-[#f5f3ff] border-2 border-[#8b5cf6] ring-4 ring-[#8b5cf6]/20 shadow-[0_8px_24px_rgba(139,92,246,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#ddd6fe]',
    tickerGlow: 'bg-[#f5f3ff] border-[#ddd6fe] text-[#7c3aed]',
  },
  DOTS_AND_BOXES: {
    type: 'DOTS_AND_BOXES',
    title: 'Dots & Boxes',
    brandTitle: 'DOTS & BOXES',
    badge: 'Strategy 2-4 Players',
    primaryColor: '#10b981',
    bgGradient: 'from-[#ccfbf1] via-[#d1fae5] to-[#e0f2fe]',
    navbarBg: 'bg-white/85 border-[#a7f3d0]',
    navbarBorder: 'border-[#a7f3d0]',
    navbarBrandGrad: 'from-[#10b981] via-[#059669] to-[#0284c7]',
    navIconBg: 'from-[#10b981] to-[#0284c7]',
    cardBorder: 'border-[#a7f3d0]',
    accentBadgeBg: 'bg-[#ecfdf5]',
    accentBadgeText: 'text-[#047857]',
    accentBadgeBorder: 'border-[#a7f3d0]',
    buttonGrad: 'from-[#10b981] via-[#059669] to-[#0284c7]',
    turnBannerMyTurn: 'bg-[#ecfdf5] border-2 border-[#10b981] ring-4 ring-[#10b981]/20 shadow-[0_8px_24px_rgba(16,185,129,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#a7f3d0]',
    tickerGlow: 'bg-[#ecfdf5] border-[#a7f3d0] text-[#047857]',
  },
  CONNECT_FOUR: {
    type: 'CONNECT_FOUR',
    title: 'Connect Four',
    brandTitle: 'CONNECT 4',
    badge: '1v1 Vertical Duel',
    primaryColor: '#2563eb',
    bgGradient: 'from-[#dbeafe] via-[#eff6ff] to-[#fef3c7]',
    navbarBg: 'bg-white/85 border-[#bfdbfe]',
    navbarBorder: 'border-[#bfdbfe]',
    navbarBrandGrad: 'from-[#2563eb] via-[#3b82f6] to-[#f59e0b]',
    navIconBg: 'from-[#2563eb] to-[#f59e0b]',
    cardBorder: 'border-[#bfdbfe]',
    accentBadgeBg: 'bg-[#eff6ff]',
    accentBadgeText: 'text-[#1d4ed8]',
    accentBadgeBorder: 'border-[#bfdbfe]',
    buttonGrad: 'from-[#2563eb] via-[#1d4ed8] to-[#f59e0b]',
    turnBannerMyTurn: 'bg-[#eff6ff] border-2 border-[#2563eb] ring-4 ring-[#2563eb]/20 shadow-[0_8px_24px_rgba(37,99,235,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#bfdbfe]',
    tickerGlow: 'bg-[#eff6ff] border-[#bfdbfe] text-[#1d4ed8]',
  },
  ROCK_PAPER_SCISSORS: {
    type: 'ROCK_PAPER_SCISSORS',
    title: 'Rock Paper Scissors',
    brandTitle: 'RPS DUEL',
    badge: 'Best of 5 Duel',
    primaryColor: '#ea580c',
    bgGradient: 'from-[#ffedd5] via-[#fff7ed] to-[#fee2e2]',
    navbarBg: 'bg-white/85 border-[#fed7aa]',
    navbarBorder: 'border-[#fed7aa]',
    navbarBrandGrad: 'from-[#ea580c] via-[#f97316] to-[#ef4444]',
    navIconBg: 'from-[#ea580c] to-[#ef4444]',
    cardBorder: 'border-[#fed7aa]',
    accentBadgeBg: 'bg-[#fff7ed]',
    accentBadgeText: 'text-[#c2410c]',
    accentBadgeBorder: 'border-[#fed7aa]',
    buttonGrad: 'from-[#ea580c] via-[#f97316] to-[#ef4444]',
    turnBannerMyTurn: 'bg-[#fff7ed] border-2 border-[#ea580c] ring-4 ring-[#ea580c]/20 shadow-[0_8px_24px_rgba(234,88,12,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#fed7aa]',
    tickerGlow: 'bg-[#fff7ed] border-[#fed7aa] text-[#c2410c]',
  },
  MEMORY: {
    type: 'MEMORY',
    title: 'Memory Match',
    brandTitle: 'MEMORY',
    badge: 'Card Flip Match',
    primaryColor: '#7c3aed',
    bgGradient: 'from-[#ede9fe] via-[#f5f3ff] to-[#fce7f3]',
    navbarBg: 'bg-white/85 border-[#ddd6fe]',
    navbarBorder: 'border-[#ddd6fe]',
    navbarBrandGrad: 'from-[#7c3aed] via-[#8b5cf6] to-[#ec4899]',
    navIconBg: 'from-[#7c3aed] to-[#ec4899]',
    cardBorder: 'border-[#ddd6fe]',
    accentBadgeBg: 'bg-[#f5f3ff]',
    accentBadgeText: 'text-[#6d28d9]',
    accentBadgeBorder: 'border-[#ddd6fe]',
    buttonGrad: 'from-[#7c3aed] via-[#6d28d9] to-[#ec4899]',
    turnBannerMyTurn: 'bg-[#f5f3ff] border-2 border-[#7c3aed] ring-4 ring-[#7c3aed]/20 shadow-[0_8px_24px_rgba(124,58,237,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#ddd6fe]',
    tickerGlow: 'bg-[#f5f3ff] border-[#ddd6fe] text-[#6d28d9]',
  },
  NUMBER_RUSH: {
    type: 'NUMBER_RUSH',
    title: 'Number Rush',
    brandTitle: 'NUMBER RUSH',
    badge: 'Speed Tap Race',
    primaryColor: '#0891b2',
    bgGradient: 'from-[#cffafe] via-[#ecfeff] to-[#d1fae5]',
    navbarBg: 'bg-white/85 border-[#a5f3fc]',
    navbarBorder: 'border-[#a5f3fc]',
    navbarBrandGrad: 'from-[#0891b2] via-[#06b6d4] to-[#10b981]',
    navIconBg: 'from-[#0891b2] to-[#10b981]',
    cardBorder: 'border-[#a5f3fc]',
    accentBadgeBg: 'bg-[#ecfeff]',
    accentBadgeText: 'text-[#0e7490]',
    accentBadgeBorder: 'border-[#a5f3fc]',
    buttonGrad: 'from-[#0891b2] via-[#06b6d4] to-[#10b981]',
    turnBannerMyTurn: 'bg-[#ecfeff] border-2 border-[#0891b2] ring-4 ring-[#0891b2]/20 shadow-[0_8px_24px_rgba(8,145,178,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#a5f3fc]',
    tickerGlow: 'bg-[#ecfeff] border-[#a5f3fc] text-[#0e7490]',
  },
  WORD_SCRAMBLE: {
    type: 'WORD_SCRAMBLE',
    title: 'Word Scramble',
    brandTitle: 'WORD SCRAMBLE',
    badge: 'Anagram Race',
    primaryColor: '#0d9488',
    bgGradient: 'from-[#ccfbf1] via-[#f0fdfa] to-[#fef3c7]',
    navbarBg: 'bg-white/85 border-[#99f6e4]',
    navbarBorder: 'border-[#99f6e4]',
    navbarBrandGrad: 'from-[#0d9488] via-[#14b8a6] to-[#f59e0b]',
    navIconBg: 'from-[#0d9488] to-[#f59e0b]',
    cardBorder: 'border-[#99f6e4]',
    accentBadgeBg: 'bg-[#f0fdfa]',
    accentBadgeText: 'text-[#0f766e]',
    accentBadgeBorder: 'border-[#99f6e4]',
    buttonGrad: 'from-[#0d9488] via-[#0f766e] to-[#f59e0b]',
    turnBannerMyTurn: 'bg-[#f0fdfa] border-2 border-[#0d9488] ring-4 ring-[#0d9488]/20 shadow-[0_8px_24px_rgba(13,148,136,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#99f6e4]',
    tickerGlow: 'bg-[#f0fdfa] border-[#99f6e4] text-[#0f766e]',
  },
  SHIP_BATTLE: {
    type: 'SHIP_BATTLE',
    title: 'Ship Battle',
    brandTitle: 'SHIP BATTLE',
    badge: '1v1 Naval Duel',
    primaryColor: '#0284c7',
    bgGradient: 'from-[#bae6fd] via-[#e0f2fe] to-[#c7d2fe]',
    navbarBg: 'bg-white/85 border-[#7dd3fc]',
    navbarBorder: 'border-[#7dd3fc]',
    navbarBrandGrad: 'from-[#0284c7] via-[#0369a1] to-[#1e3a8a]',
    navIconBg: 'from-[#0284c7] to-[#1e3a8a]',
    cardBorder: 'border-[#7dd3fc]',
    accentBadgeBg: 'bg-[#e0f2fe]',
    accentBadgeText: 'text-[#0369a1]',
    accentBadgeBorder: 'border-[#7dd3fc]',
    buttonGrad: 'from-[#0284c7] via-[#0369a1] to-[#1e3a8a]',
    turnBannerMyTurn: 'bg-[#e0f2fe] border-2 border-[#0284c7] ring-4 ring-[#0284c7]/20 shadow-[0_8px_24px_rgba(2,132,199,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#7dd3fc]',
    tickerGlow: 'bg-[#e0f2fe] border-[#7dd3fc] text-[#0369a1]',
  },
  MASTERMIND: {
    type: 'MASTERMIND',
    title: 'Mastermind Duel',
    brandTitle: 'MASTERMIND',
    badge: 'Codebreaker',
    primaryColor: '#6366f1',
    bgGradient: 'from-[#e0e7ff] via-[#ede9fe] to-[#fbcfe8]',
    navbarBg: 'bg-white/85 border-[#c7d2fe]',
    navbarBorder: 'border-[#c7d2fe]',
    navbarBrandGrad: 'from-[#6366f1] via-[#8b5cf6] to-[#ec4899]',
    navIconBg: 'from-[#4f46e5] to-[#7c3aed]',
    cardBorder: 'border-[#c7d2fe]',
    accentBadgeBg: 'bg-[#e0e7ff]',
    accentBadgeText: 'text-[#4338ca]',
    accentBadgeBorder: 'border-[#c7d2fe]',
    buttonGrad: 'from-[#6366f1] via-[#8b5cf6] to-[#a855f7]',
    turnBannerMyTurn: 'bg-[#e0e7ff] border-2 border-[#6366f1]',
    turnBannerWaiting: 'bg-white/90 border-[#c7d2fe]',
    tickerGlow: 'bg-[#e0e7ff] text-[#4338ca] border-[#c7d2fe]',
  },
  LUDO: {
    type: 'LUDO',
    title: 'Ludo Party',
    brandTitle: 'LUDO',
    badge: 'Board Classic',
    primaryColor: '#eab308',
    bgGradient: 'from-[#fef9c3] via-[#ffedd5] to-[#fef08a]',
    navbarBg: 'bg-white/85 border-[#fde047]',
    navbarBorder: 'border-[#fde047]',
    navbarBrandGrad: 'from-[#eab308] via-[#f59e0b] to-[#ef4444]',
    navIconBg: 'from-[#ca8a04] to-[#ea580c]',
    cardBorder: 'border-[#fde047]',
    accentBadgeBg: 'bg-[#fef9c3]',
    accentBadgeText: 'text-[#a16207]',
    accentBadgeBorder: 'border-[#fde047]',
    buttonGrad: 'from-[#eab308] via-[#f59e0b] to-[#ea580c]',
    turnBannerMyTurn: 'bg-[#fef9c3] border-2 border-[#eab308]',
    turnBannerWaiting: 'bg-white/90 border-[#fde047]',
    tickerGlow: 'bg-[#fef9c3] text-[#a16207] border-[#fde047]',
  },
  DETECTIVE_MYSTERY: {
    type: 'DETECTIVE_MYSTERY',
    title: 'Detective Mystery',
    brandTitle: 'DETECTIVE',
    badge: 'Clue Deduction',
    primaryColor: '#d97706',
    bgGradient: 'from-[#fef3c7] via-[#fed7aa] to-[#fef9c3]',
    navbarBg: 'bg-white/85 border-[#fde68a]',
    navbarBorder: 'border-[#fde68a]',
    navbarBrandGrad: 'from-[#d97706] via-[#b45309] to-[#78350f]',
    navIconBg: 'from-[#b45309] to-[#78350f]',
    cardBorder: 'border-[#fde68a]',
    accentBadgeBg: 'bg-[#fef3c7]',
    accentBadgeText: 'text-[#92400e]',
    accentBadgeBorder: 'border-[#fde68a]',
    buttonGrad: 'from-[#d97706] via-[#b45309] to-[#78350f]',
    turnBannerMyTurn: 'bg-[#fef3c7] border-2 border-[#d97706]',
    turnBannerWaiting: 'bg-white/90 border-[#fde68a]',
    tickerGlow: 'bg-[#fef3c7] text-[#92400e] border-[#fde68a]',
  },
  SUDOKU_BATTLE: {
    type: 'SUDOKU_BATTLE',
    title: 'Sudoku Battle',
    brandTitle: 'SUDOKU',
    badge: 'Number Clash',
    primaryColor: '#06b6d4',
    bgGradient: 'from-[#cffafe] via-[#e0e7ff] to-[#ecfeff]',
    navbarBg: 'bg-white/85 border-[#a5f3fc]',
    navbarBorder: 'border-[#a5f3fc]',
    navbarBrandGrad: 'from-[#06b6d4] via-[#0891b2] to-[#4f46e5]',
    navIconBg: 'from-[#0891b2] to-[#4f46e5]',
    cardBorder: 'border-[#a5f3fc]',
    accentBadgeBg: 'bg-[#cffafe]',
    accentBadgeText: 'text-[#0e7490]',
    accentBadgeBorder: 'border-[#a5f3fc]',
    buttonGrad: 'from-[#06b6d4] via-[#0891b2] to-[#4f46e5]',
    turnBannerMyTurn: 'bg-[#cffafe] border-2 border-[#06b6d4]',
    turnBannerWaiting: 'bg-white/90 border-[#a5f3fc]',
    tickerGlow: 'bg-[#cffafe] text-[#0e7490] border-[#a5f3fc]',
  },
  BATTLE_2048: {
    type: 'BATTLE_2048',
    title: '2048 Battle',
    brandTitle: '2048',
    badge: 'Tile Merger',
    primaryColor: '#f97316',
    bgGradient: 'from-[#fed7aa] via-[#fef3c7] to-[#ffedd5]',
    navbarBg: 'bg-white/85 border-[#fdba74]',
    navbarBorder: 'border-[#fdba74]',
    navbarBrandGrad: 'from-[#f97316] via-[#ea580c] to-[#c2410c]',
    navIconBg: 'from-[#ea580c] to-[#c2410c]',
    cardBorder: 'border-[#fdba74]',
    accentBadgeBg: 'bg-[#fed7aa]',
    accentBadgeText: 'text-[#9a3412]',
    accentBadgeBorder: 'border-[#fdba74]',
    buttonGrad: 'from-[#f97316] via-[#ea580c] to-[#c2410c]',
    turnBannerMyTurn: 'bg-[#fed7aa] border-2 border-[#f97316]',
    turnBannerWaiting: 'bg-white/90 border-[#fdba74]',
    tickerGlow: 'bg-[#fed7aa] text-[#9a3412] border-[#fdba74]',
  },
  CHECKERS: {
    type: 'CHECKERS',
    title: 'Checkers Duel',
    brandTitle: 'CHECKERS',
    badge: 'Board Crown',
    primaryColor: '#b45309',
    bgGradient: 'from-[#fef3c7] via-[#ffedd5] to-[#fef9c3]',
    navbarBg: 'bg-white/85 border-[#fde68a]',
    navbarBorder: 'border-[#fde68a]',
    navbarBrandGrad: 'from-[#b45309] via-[#92400e] to-[#78350f]',
    navIconBg: 'from-[#92400e] to-[#78350f]',
    cardBorder: 'border-[#fde68a]',
    accentBadgeBg: 'bg-[#fef3c7]',
    accentBadgeText: 'text-[#78350f]',
    accentBadgeBorder: 'border-[#fde68a]',
    buttonGrad: 'from-[#b45309] via-[#92400e] to-[#78350f]',
    turnBannerMyTurn: 'bg-[#fef3c7] border-2 border-[#b45309]',
    turnBannerWaiting: 'bg-white/90 border-[#fde68a]',
    tickerGlow: 'bg-[#fef3c7] text-[#78350f] border-[#fde68a]',
  },
  CARD_BATTLE: {
    type: 'CARD_BATTLE',
    title: 'Card Battle Arena',
    brandTitle: 'CARD BATTLE',
    badge: 'Deck Strategy',
    primaryColor: '#f43f5e',
    bgGradient: 'from-[#fecdd3] via-[#ffe4e6] to-[#fce7f3]',
    navbarBg: 'bg-white/85 border-[#fda4af]',
    navbarBorder: 'border-[#fda4af]',
    navbarBrandGrad: 'from-[#f43f5e] via-[#e11d48] to-[#be123c]',
    navIconBg: 'from-[#e11d48] to-[#be123c]',
    cardBorder: 'border-[#fda4af]',
    accentBadgeBg: 'bg-[#fecdd3]',
    accentBadgeText: 'text-[#9f1239]',
    accentBadgeBorder: 'border-[#fda4af]',
    buttonGrad: 'from-[#f43f5e] via-[#e11d48] to-[#be123c]',
    turnBannerMyTurn: 'bg-[#fecdd3] border-2 border-[#f43f5e]',
    turnBannerWaiting: 'bg-white/90 border-[#fda4af]',
    tickerGlow: 'bg-[#fecdd3] text-[#9f1239] border-[#fda4af]',
  },
  CHESS: {
    type: 'CHESS',
    title: 'Chess Grandmaster',
    brandTitle: 'CHESS',
    badge: 'Classic 1v1',
    primaryColor: '#4338ca',
    bgGradient: 'from-[#e0e7ff] via-[#ede9fe] to-[#f3e8ff]',
    navbarBg: 'bg-white/85 border-[#c7d2fe]',
    navbarBorder: 'border-[#c7d2fe]',
    navbarBrandGrad: 'from-[#4338ca] via-[#3730a3] to-[#312e81]',
    navIconBg: 'from-[#3730a3] to-[#312e81]',
    cardBorder: 'border-[#c7d2fe]',
    accentBadgeBg: 'bg-[#e0e7ff]',
    accentBadgeText: 'text-[#312e81]',
    accentBadgeBorder: 'border-[#c7d2fe]',
    buttonGrad: 'from-[#4338ca] via-[#3730a3] to-[#312e81]',
    turnBannerMyTurn: 'bg-[#e0e7ff] border-2 border-[#4338ca]',
    turnBannerWaiting: 'bg-white/90 border-[#c7d2fe]',
    tickerGlow: 'bg-[#e0e7ff] text-[#312e81] border-[#c7d2fe]',
  },
  PIRATE_BATTLE: {
    type: 'PIRATE_BATTLE',
    title: 'Pirate Battle',
    brandTitle: 'PIRATES',
    badge: 'High Seas War',
    primaryColor: '#0f172a',
    bgGradient: 'from-[#cbd5e1] via-[#e2e8f0] to-[#f1f5f9]',
    navbarBg: 'bg-white/85 border-[#94a3b8]',
    navbarBorder: 'border-[#94a3b8]',
    navbarBrandGrad: 'from-[#0f172a] via-[#1e293b] to-[#334155]',
    navIconBg: 'from-[#0f172a] to-[#334155]',
    cardBorder: 'border-[#94a3b8]',
    accentBadgeBg: 'bg-[#e2e8f0]',
    accentBadgeText: 'text-[#0f172a]',
    accentBadgeBorder: 'border-[#94a3b8]',
    buttonGrad: 'from-[#0f172a] via-[#1e293b] to-[#334155]',
    turnBannerMyTurn: 'bg-[#e2e8f0] border-2 border-[#0f172a]',
    turnBannerWaiting: 'bg-white/90 border-[#94a3b8]',
    tickerGlow: 'bg-[#e2e8f0] text-[#0f172a] border-[#94a3b8]',
  },
  DEFAULT: {
    type: 'DEFAULT',
    title: 'Multi Arcade',
    brandTitle: 'ARCADE HUB',
    badge: 'Multiplayer Games',
    primaryColor: '#8b7fe8',
    bgGradient: 'from-[#d9d2fa] via-[#e8e2fc] to-[#fde2ea]',
    navbarBg: 'bg-white/80 border-[#ede8f8]',
    navbarBorder: 'border-[#ede8f8]',
    navbarBrandGrad: 'from-[#f8788a] via-[#e271a5] to-[#8b7fe8]',
    navIconBg: 'from-[#f8788a] via-[#e271a5] to-[#8b7fe8]',
    cardBorder: 'border-[#ede8f8]',
    accentBadgeBg: 'bg-[#f0ecfc]',
    accentBadgeText: 'text-[#6d5ebd]',
    accentBadgeBorder: 'border-[#e0d6f8]',
    buttonGrad: 'from-[#f8788a] via-[#e271a5] to-[#8b7fe8]',
    turnBannerMyTurn: 'bg-[#f0ecfc] border-2 border-[#8b7fe8] ring-4 ring-[#8b7fe8]/20 shadow-[0_8px_24px_rgba(139,127,232,0.25)]',
    turnBannerWaiting: 'bg-white/90 border-[#ede8f8]',
    tickerGlow: 'bg-[#f0ecfc] border-[#e0d6f8] text-[#6d5ebd]',
  },
};

export const getGameTheme = (gameType?: GameType | 'DEFAULT' | null): GameThemeConfig => {
  if (gameType && GAME_THEMES[gameType]) {
    return GAME_THEMES[gameType];
  }
  return GAME_THEMES.DEFAULT;
};
